server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    types {
        application/wasm wasm;
        application/javascript js;
        application/octet-stream data;
    }

    location ~* \.(js)$ {
        add_header Content-Type application/javascript;
    }

    location ~* \.(wasm)$ {
        add_header Content-Type application/wasm;
    }

    location ~* \.(data)$ {
        add_header Content-Type application/octet-stream;
    }

    gzip off;
}